name: sql_to_ibis
channels:
  - conda-forge
dependencies:
  # required
  - ibis-framework=1.3.0
  - lark-parser=0.8.5

  # Test requirements
  - black
  - flake8
  - mypy
  - isort
  - pytest
  - pandas
  - pytest
  - pytest-cov
  - freezegun
