name: sql_to_ibis
channels:
  - conda-forge
dependencies:
  # required
  - lark-parser=0.8.5

  # Test requirements
  - black=20.8b1
  - flake8
  - mypy
  - isort
  - pytest
  - pandas
  - pytest
  - pytest-cov
  - freezegun

  - pip
  - pip:
      - ibis-framework==1.3.0
